<a href="https://colab.research.google.com/github/01PrathamS/PyTorch_Exercises/blob/main/Fundamentals_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
## Importing libraries

import torch 

1. Documentation Reading: 

In [3]:
## 2. Create a random tensor with shape (7,7).

x = torch.rand(size=(7,7))
x

tensor([[9.0259e-01, 5.0781e-01, 1.3314e-01, 3.5451e-01, 4.3116e-01, 3.1880e-01,
         6.3151e-04],
        [3.2774e-02, 4.0985e-01, 5.0401e-01, 7.6032e-01, 4.3703e-01, 1.1860e-01,
         4.2973e-01],
        [7.1796e-02, 1.7745e-01, 5.4714e-01, 3.8834e-01, 6.1522e-01, 6.5524e-01,
         6.7734e-01],
        [3.3674e-01, 1.1252e-02, 2.6625e-01, 7.4670e-01, 1.3211e-01, 3.5471e-01,
         4.2798e-01],
        [8.3224e-01, 7.1302e-01, 7.0972e-01, 2.7156e-01, 8.7889e-02, 4.2590e-01,
         5.9953e-01],
        [4.1071e-01, 7.3475e-01, 8.7358e-01, 7.2868e-01, 1.2123e-01, 2.2631e-01,
         6.4460e-01],
        [2.9392e-01, 7.7898e-01, 8.0910e-01, 4.0974e-01, 8.6432e-01, 2.1000e-01,
         4.2081e-02]])

In [4]:
## 3.Perform a matrix multiplication on the tensor from 2 with 
#    another random tensor with shape (1, 7)

y = torch.rand(size=(1,7))
y

## matrix multiplication between x and y 

z = torch.matmul(x, y.T)
z, z.shape

(tensor([[1.3810],
         [1.6357],
         [1.7418],
         [1.2469],
         [1.4891],
         [1.8162],
         [2.0260]]),
 torch.Size([7, 1]))

In [5]:
## 4. Set the random seed to 0 and do exercises 2 & 3 over again.

torch.manual_seed(0) 

a = torch.rand(size=(7,7))
b = torch.rand(size=(1,7))

c = torch.mm(a, b.T)
c, c.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

In [6]:
""" 5. Speaking of random seeds, we saw how to set it with
 torch.manual_seed() but is there a GPU equivalent? 
 (hint: you'll need to look into the documentation 
 for torch.cuda for this one). If there is, set the GPU random seed to 1234."""

if torch.cuda.is_available():
  torch.cuda.manual_seed(1234)
else:
  torch.manual_seed(42)

device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

6.Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).


to solve this runtime --> change runtime type --> hardwarre accelerator --> change it to gpu.

In [8]:
torch.manual_seed(1234)

a = torch.rand(size=(2,3)).to(device)
b = torch.rand(size=(2,3)).to(device)

a, b

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [9]:
# 7.Perform a matrix multiplication on the tensors you created in 6

d = torch.matmul(a, b.T)
d

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

In [11]:
## find the maximum and minimum of the output 7 

print('max of output is:', torch.max(d))
print('min of output is:', torch.min(d))

max of output is: tensor(0.5617, device='cuda:0')
min of output is: tensor(0.3647, device='cuda:0')


In [12]:
## find the index of maximum and minimum of the output 7 

print('index of maximum of output is: ', torch.argmax(d))
print('index of minumum of output is: ', torch.argmin(d))

index of maximum of output is:  tensor(3, device='cuda:0')
index of minumum of output is:  tensor(0, device='cuda:0')


10.Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape

In [19]:
torch.manual_seed(7)

tens = torch.rand(size=(1,1,1,10))
tens.shape

tens_1 = tens.squeeze()

print(tens, tens.shape)
print(tens_1, tens_1.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
